### ISSUE TITLE
v0.3.0-beta won't launch

### ISSUE THREAD

**Issue by johnblommers** [iaacornus/simtex#6]
We install simtex

```bash
python3 -m pip install simtex --user
```

Check it's install location

```bash
which simtex
/home/johnb/.local/bin/simtex
```

And launch it

```bash
simtex --help  File "/home/johnb/.local/bin/simtex", line 8, in <module>
    sys.exit(main())
  File "/home/johnb/.local/lib/python3.10/site-packages/src/main.py", line 7, in main
    cli_: Cli = Cli()
  File "/home/johnb/.local/lib/python3.10/site-packages/src/cli.py", line 19, in __init__
    self.config: Config = conf_parse.conf()
  File "/home/johnb/.local/lib/python3.10/site-packages/src/utils/config_fetch.py", line 121, in conf
    raw_conf["COMPILER"],
KeyError: 'COMPILER'
```

This happens identically on two different systems.

**Comment by iaacornus** [comment]
is the old config file updated? There are new parameters that were included, which causes the parser to break if not found, as of now, I haven't yet included a way to automatically update the config file in the packaging, but I'm working on it. And it is also good to note that the beta version was not merged in main branch yet, so the links that points to the config file in the main branch is also not update. So for now, the issue can be worked around by updating the config file manually with the [config file in devel branch](https://github.com/iaacornus/simtex/blob/devel/examples/config/simtex.json). Thank you.

**Comment by johnblommers** [comment]
Understood. Updating `simtex.json` fixed the issue.

And looking inside it I see the variable `COMPILER` which was absent in the old file.
